### ISSUE TITLE
Does Ollama costs Money?

### ISSUE THREAD

**Issue by Itseliganee** [clevaway/J.A.R.V.I.S#14]
I don't find anything. :(

**Comment by FotieMConstant** [comment]
Ollama is free and open source. Could you be more explicit about what you mean by “I can’t find anything “? If you have any questions, please feel free to drop them below

**Comment by Itseliganee** [comment]
Thanks. I mean when i say something to ollama, do i need to pay in Credits? Because i saw some Prices when i searched: Ollama Price.

**Comment by FotieMConstant** [comment]
You do not need to pay anything, it runs locally on your computer

**Comment by Itseliganee** [comment]
I found this: https://gist.github.com/jerzydziewierz/3b4a169c8d7cba89e18f613b32c3f52b

**Comment by FotieMConstant** [comment]
I see. however, ollama is free and open source software itself. 
you might wanna check this: https://github.com/ollama/ollama

ps: if this issue is no longer relevant could we close it? thanks

**Comment by Itseliganee** [comment]
of course. thx for the help :D
